# Generated by Django 5.1.3 on 2024-11-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='Project',
        ),
    ]
