# Generated by Django 5.1.3 on 2024-11-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_plant_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_explanation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='read_more_link',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_brief',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_model',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
